static_config:
  bot_type: "drissionpage"
  custom_user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36"
  custom_headers:
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36"
    Accept: "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8"
    Accept-Language: "zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7"
    Cache-Control: "no-cache"
    Connection: "keep-alive"
    Referer: "https://www.v2ph.com/"
    sec-fetch-dest: "image"
    sec-fetch-mode: "no-cors"
    sec-fetch-site: "same-site"
  language: "zh"
  chrome_args: null
  no_metadata: false
  force_download: false
  terminate: false
  use_default_chrome_profile: false
  log_level: 1000
  min_scroll_distance: 1000
  max_scroll_distance: 2000
  min_scroll_step: 300
  max_scroll_step: 500
  max_worker: 2
  rate_limit: 1000
  page_range: ""
  # path relative configurations
  cookies_path: ""
  download_dir: ""
  metadata_path: ""
  download_log_path: ""
  system_log_path: ""
  chrome_exec_path:
    Linux: "/usr/bin/google-chrome"
    Darwin: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
    Windows: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
  chrome_profile_path: ""

runtime_config:
  url: ""
  url_file: ""

encryption_config:
  key_bytes: 32
  salt_bytes: 16
  nonce_bytes: 24
  kdf_ops_limit: 16
  kdf_mem_limit: 8192
